### ISSUE TITLE
Any plan to upstream or add license?

### ISSUE THREAD

**Issue by jhg03a** [r3nic1e/telegraf-clickhouse-plugin#1]
Is there any plan to upstream this plugin into the telegraf project or license the code in a compatible way for others to do it?

**Comment by r3nic1e** [comment]
I think I gave influxdata enough time to implement external plugins :)

Anyways I am sorry for ignoring your question. I just stopped using telegraf several weeks after last commit (and still don't use it). So I decided to add support launching it via `[[outputs.execd]]` (https://github.com/influxdata/telegraf/blob/master/plugins/common/shim/README.md)

Tested a bit, but cannot do it in production :)
