### ISSUE TITLE
Telegraf SQL output now supports Clickhouse

### ISSUE THREAD

**Issue by bojdell** [r3nic1e/telegraf-clickhouse-plugin#22]
Thanks for your work on this! Just FYI - as of Jan 2022, Clickhouse is now supported by the telegraf [SQL output plugin](https://github.com/influxdata/telegraf/tree/86cad6c2e208fde9177236475ddfa4be865d5eeb/plugins/outputs/sql) (https://github.com/influxdata/telegraf/pull/9671)

**Comment by r3nic1e** [comment]
I appreciate you for notifying! Haven't used telegraf for a long time so didn't know about this.
